Vagrant.configure("2") do |config|

# Box settings
  config.vm.box_url ="http://files.vagrantup.com/precise32.box"
  config.vm.box = "precise32"

# Guest settings
  config.vm.guest = "linux"
  config.vm.hostname = "www.oxiddemo.de"

# Network settings
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.network :forwarded_port, host: 4443, guest: 443

# Synced folders
  config.vm.synced_folder "templates", "/tmp/vagrant-puppet/templates"

# Provisioning with puppet
  config.vm.provision :puppet do |puppet|
    puppet.options        = " --verbose --debug --no-daemonize"
    puppet.options        = [ "--templatedir", "/tmp/vagrant-puppet/templates" ]
    puppet.manifests_path = "manifests"
    puppet.module_path    = "modules"
    puppet.manifest_file  = "site.pp"
  end

# Provisioning with script
  config.vm.provision :shell, :path => "oxid_bootstrap.sh"
end
